### ISSUE TITLE
geom_basketball NCAA three point line

### ISSUE THREAD

**Issue by mileskee** [sportsdataverse/sportyR#29]
Is there a way to only show one of the three point lines when using geom_basketball with the NCAA court?

**Comment by rossdrucker** [comment]
They'll both be plotted by default, but you can set the color of one of them to be the same as the half court colors that they're on top of

For example, this uses the default colors but will only display one of the three-point arcs:

```r
library(sportyR)

geom_basketball(
  league = "ncaa", 
  color_updates = list(
    three_point_lines = c(
      # outer line first, this one will be displayed
      "#000000",
      # inner line same color as background; may need to match to
      # either two-point range or half court colors
      "#d2ab6f"
    )
  )
)
```
![image](https://github.com/sportsdataverse/sportyR/assets/15791518/ab9f4d7d-7317-48e4-8e3d-726304483f97)
